header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/.gitignore'
    - '**/*.yaml'
    - '**/*.golden'
    - '**/*.yaml.injected'
    - '**/*.ttf'
    - '**/*.woff'
    - '**/*.woff2'
    - '**/*.eot'
    - '**/*.svg'
    - '**/*.pem'
    - '**/*.tpl'
    - '**/*.tar.gz'
    - 'pilot/docker'

  comment: on-failure

  dependency:
    files:
      - go.mod