header:
  license:
    spdx-id: Apache-2.0
#    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'go.mod'
    - 'go.sum'
    - '**/.gitmodules'
    - '**/.gitattributes'
    - '**/.gitignore'
    - '**/*.yaml'
    - '**/*.golden'
    - '**/*.injected'
    - '**/*.ttf'
    - '**/*.json'
    - '**/*.woff'
    - '**/*.woff2'
    - '**/*.eot'
    - '**/*.svg'
    - '**/*.pem'
    - '**/*.crt'
    - '**/*.key'
    - '**/*.tpl'
    - '**/*.tmpl'
    - '**/*.tar.gz'
    - '**/*.proxycfg'
    - 'pilot/docker'
    - 'pkg/test/echo/docker'

  comment: on-failure

  dependency:
    files:
      - go.mod